[package]
name = "katsite"
license = "MIT"
version = "0.1.0"
authors = ["katattakd <katattakd@pm.me>"]

[dependencies]
ammonia = "3.1.0"
comrak = "0.7.0"
glob = "0.3.0"
hyperbuild = "0.0.44"
rayon = "1.3.0"
serde = "1.0.106"
serde_derive = "1.0.106"
toml = "0.5.6"

[profile.dev]
rpath = true

[profile.release]
lto = true
panic = 'abort'

[profile.bench]
lto = true
