[markdown] # Markdown parser settings. These are best left at defaults, changing them can break some plugins.
convert_line_breaks = false # Convert soft line breaks (newlines) into hard line breaks.
convert_punctuation = true # Convert simple punctuation into smart punctuation (curly quotes).
enable_raw_html_inlining = true # Allow inline HTML to be used in markdown files.
enable_github_extensions = true # Enable GitHub markdown extensions (strikethrough, tables, automatic links, task lists.
enable_comrak_extensions = true # Enable Comrak markdown extensions (superscript, footnotes, description lists).

[plugins] # KatSite plugin settings
enable_core = true # Core is a built-in plugin that adds a doctype and viewport, and should not be disabled unless necessary.
plugins_list = ["basic-navbar.sh", "basic-theme.sh", "minifier.sh"] # Load built-in plugins in this order.

